# Adapted from https://github.com/JamesIves/github-pages-deploy-action
name: Build and Deploy GitHub Hosted PLDB
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
      - name: Install and Build
        run: |
          rm .gitignore
          npm install .
          npm run tsc
          npm run build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: github.pldb.com # The branch the action should deploy to.
          folder: site
